# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='element_identifier',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='action',
            name='locators',
            field=models.CharField(blank=True, choices=[['ID', 'ID'], ['NAME', 'Name'], ['XPATH', 'X Path'], ['CSSSELECTOR', 'CSS Selector'], ['LINKTEXT', 'Link Text'], ['CLASSNAME', 'Class Name'], ['TAGNAME', 'Tag Name'], ['PARTIALLINKTEXT', 'Partial Link Text']], max_length=255),
        ),
    ]
