# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0002_auto_20170609_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=500)),
                ('report', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.UseCase')),
            ],
        ),
    ]
