# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0006_auto_20170628_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.Project')),
            ],
            options={
                'ordering': ['name', 'project__name'],
            },
        ),
        migrations.AddField(
            model_name='usecase',
            name='job',
            field=models.ManyToManyField(to='qa_app.Jobs'),
        ),
    ]
