# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0008_auto_20170630_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUseCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.Jobs')),
            ],
            options={
                'ordering': ['job__name', 'seq'],
            },
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='job',
        ),
        migrations.AddField(
            model_name='jobusecases',
            name='usecase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.UseCase'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='jobs',
            field=models.ManyToManyField(through='qa_app.JobUseCases', to='qa_app.Jobs'),
        ),
    ]
