# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0003_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[['Click', 'Click'], ['EnterText', 'Enter Text'], ['SelectFromDropDown', 'Select From Drop Down'], ['SelectFromLookUp', 'Select From Look Up'], ['URL', 'URL'], ['PAUSE', 'PAUSE']], max_length=255),
        ),
    ]
