# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0007_auto_20170628_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, help_text='A description of this Action', verbose_name='Description'),
        ),
    ]
